// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package edu.umich.penning;

public final class EventProtocol {
  private EventProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userID = 1;
    /**
     * <code>required string userID = 1;</code>
     */
    boolean hasUserID();
    /**
     * <code>required string userID = 1;</code>
     */
    java.lang.String getUserID();
    /**
     * <code>required string userID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIDBytes();

    // required string sessionID = 2;
    /**
     * <code>required string sessionID = 2;</code>
     */
    boolean hasSessionID();
    /**
     * <code>required string sessionID = 2;</code>
     */
    java.lang.String getSessionID();
    /**
     * <code>required string sessionID = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    // required int32 eventID = 3;
    /**
     * <code>required int32 eventID = 3;</code>
     */
    boolean hasEventID();
    /**
     * <code>required int32 eventID = 3;</code>
     */
    int getEventID();

    // required .penning.Event.EventType type = 4;
    /**
     * <code>required .penning.Event.EventType type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required .penning.Event.EventType type = 4;</code>
     */
    edu.umich.penning.EventProtocol.Event.EventType getType();

    // optional int32 cursorLocation = 5;
    /**
     * <code>optional int32 cursorLocation = 5;</code>
     */
    boolean hasCursorLocation();
    /**
     * <code>optional int32 cursorLocation = 5;</code>
     */
    int getCursorLocation();

    // optional string text = 6;
    /**
     * <code>optional string text = 6;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 6;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 6;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code penning.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessionID_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              eventID_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              edu.umich.penning.EventProtocol.Event.EventType value = edu.umich.penning.EventProtocol.Event.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cursorLocation_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.penning.EventProtocol.internal_static_penning_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.penning.EventProtocol.internal_static_penning_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.penning.EventProtocol.Event.class, edu.umich.penning.EventProtocol.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code penning.Event.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INSERT = 0;</code>
       */
      INSERT(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      /**
       * <code>UNDO = 2;</code>
       */
      UNDO(2, 2),
      /**
       * <code>REDO = 3;</code>
       */
      REDO(3, 3),
      /**
       * <code>CURSORLOCATIONCHANGED = 4;</code>
       */
      CURSORLOCATIONCHANGED(4, 4),
      ;

      /**
       * <code>INSERT = 0;</code>
       */
      public static final int INSERT_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;
      /**
       * <code>UNDO = 2;</code>
       */
      public static final int UNDO_VALUE = 2;
      /**
       * <code>REDO = 3;</code>
       */
      public static final int REDO_VALUE = 3;
      /**
       * <code>CURSORLOCATIONCHANGED = 4;</code>
       */
      public static final int CURSORLOCATIONCHANGED_VALUE = 4;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return INSERT;
          case 1: return DELETE;
          case 2: return UNDO;
          case 3: return REDO;
          case 4: return CURSORLOCATIONCHANGED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.umich.penning.EventProtocol.Event.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:penning.Event.EventType)
    }

    private int bitField0_;
    // required string userID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userID_;
    /**
     * <code>required string userID = 1;</code>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userID = 1;</code>
     */
    public java.lang.String getUserID() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string sessionID = 2;
    public static final int SESSIONID_FIELD_NUMBER = 2;
    private java.lang.Object sessionID_;
    /**
     * <code>required string sessionID = 2;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sessionID = 2;</code>
     */
    public java.lang.String getSessionID() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 eventID = 3;
    public static final int EVENTID_FIELD_NUMBER = 3;
    private int eventID_;
    /**
     * <code>required int32 eventID = 3;</code>
     */
    public boolean hasEventID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 eventID = 3;</code>
     */
    public int getEventID() {
      return eventID_;
    }

    // required .penning.Event.EventType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private edu.umich.penning.EventProtocol.Event.EventType type_;
    /**
     * <code>required .penning.Event.EventType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .penning.Event.EventType type = 4;</code>
     */
    public edu.umich.penning.EventProtocol.Event.EventType getType() {
      return type_;
    }

    // optional int32 cursorLocation = 5;
    public static final int CURSORLOCATION_FIELD_NUMBER = 5;
    private int cursorLocation_;
    /**
     * <code>optional int32 cursorLocation = 5;</code>
     */
    public boolean hasCursorLocation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 cursorLocation = 5;</code>
     */
    public int getCursorLocation() {
      return cursorLocation_;
    }

    // optional string text = 6;
    public static final int TEXT_FIELD_NUMBER = 6;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 6;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userID_ = "";
      sessionID_ = "";
      eventID_ = 0;
      type_ = edu.umich.penning.EventProtocol.Event.EventType.INSERT;
      cursorLocation_ = 0;
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessionIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, eventID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, cursorLocation_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessionIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, eventID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cursorLocation_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.penning.EventProtocol.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.penning.EventProtocol.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.penning.EventProtocol.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.penning.EventProtocol.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.penning.EventProtocol.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code penning.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.penning.EventProtocol.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.penning.EventProtocol.internal_static_penning_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.penning.EventProtocol.internal_static_penning_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.penning.EventProtocol.Event.class, edu.umich.penning.EventProtocol.Event.Builder.class);
      }

      // Construct using edu.umich.penning.EventProtocol.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        eventID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = edu.umich.penning.EventProtocol.Event.EventType.INSERT;
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorLocation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.penning.EventProtocol.internal_static_penning_Event_descriptor;
      }

      public edu.umich.penning.EventProtocol.Event getDefaultInstanceForType() {
        return edu.umich.penning.EventProtocol.Event.getDefaultInstance();
      }

      public edu.umich.penning.EventProtocol.Event build() {
        edu.umich.penning.EventProtocol.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.penning.EventProtocol.Event buildPartial() {
        edu.umich.penning.EventProtocol.Event result = new edu.umich.penning.EventProtocol.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionID_ = sessionID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.eventID_ = eventID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cursorLocation_ = cursorLocation_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.penning.EventProtocol.Event) {
          return mergeFrom((edu.umich.penning.EventProtocol.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.penning.EventProtocol.Event other) {
        if (other == edu.umich.penning.EventProtocol.Event.getDefaultInstance()) return this;
        if (other.hasUserID()) {
          bitField0_ |= 0x00000001;
          userID_ = other.userID_;
          onChanged();
        }
        if (other.hasSessionID()) {
          bitField0_ |= 0x00000002;
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (other.hasEventID()) {
          setEventID(other.getEventID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCursorLocation()) {
          setCursorLocation(other.getCursorLocation());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000020;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserID()) {
          
          return false;
        }
        if (!hasSessionID()) {
          
          return false;
        }
        if (!hasEventID()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.penning.EventProtocol.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.penning.EventProtocol.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userID = 1;
      private java.lang.Object userID_ = "";
      /**
       * <code>required string userID = 1;</code>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public java.lang.String getUserID() {
        java.lang.Object ref = userID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIDBytes() {
        java.lang.Object ref = userID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder setUserID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = getDefaultInstance().getUserID();
        onChanged();
        return this;
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder setUserIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }

      // required string sessionID = 2;
      private java.lang.Object sessionID_ = "";
      /**
       * <code>required string sessionID = 2;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sessionID = 2;</code>
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionID = 2;</code>
       */
      public Builder setSessionID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionID = 2;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionID = 2;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionID_ = value;
        onChanged();
        return this;
      }

      // required int32 eventID = 3;
      private int eventID_ ;
      /**
       * <code>required int32 eventID = 3;</code>
       */
      public boolean hasEventID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 eventID = 3;</code>
       */
      public int getEventID() {
        return eventID_;
      }
      /**
       * <code>required int32 eventID = 3;</code>
       */
      public Builder setEventID(int value) {
        bitField0_ |= 0x00000004;
        eventID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 eventID = 3;</code>
       */
      public Builder clearEventID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventID_ = 0;
        onChanged();
        return this;
      }

      // required .penning.Event.EventType type = 4;
      private edu.umich.penning.EventProtocol.Event.EventType type_ = edu.umich.penning.EventProtocol.Event.EventType.INSERT;
      /**
       * <code>required .penning.Event.EventType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .penning.Event.EventType type = 4;</code>
       */
      public edu.umich.penning.EventProtocol.Event.EventType getType() {
        return type_;
      }
      /**
       * <code>required .penning.Event.EventType type = 4;</code>
       */
      public Builder setType(edu.umich.penning.EventProtocol.Event.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .penning.Event.EventType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = edu.umich.penning.EventProtocol.Event.EventType.INSERT;
        onChanged();
        return this;
      }

      // optional int32 cursorLocation = 5;
      private int cursorLocation_ ;
      /**
       * <code>optional int32 cursorLocation = 5;</code>
       */
      public boolean hasCursorLocation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 cursorLocation = 5;</code>
       */
      public int getCursorLocation() {
        return cursorLocation_;
      }
      /**
       * <code>optional int32 cursorLocation = 5;</code>
       */
      public Builder setCursorLocation(int value) {
        bitField0_ |= 0x00000010;
        cursorLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLocation = 5;</code>
       */
      public Builder clearCursorLocation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cursorLocation_ = 0;
        onChanged();
        return this;
      }

      // optional string text = 6;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 6;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:penning.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:penning.Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_penning_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_penning_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\007penning\"\335\001\n\005Event\022\016\n\006user" +
      "ID\030\001 \002(\t\022\021\n\tsessionID\030\002 \002(\t\022\017\n\007eventID\030\003" +
      " \002(\005\022&\n\004type\030\004 \002(\0162\030.penning.Event.Event" +
      "Type\022\026\n\016cursorLocation\030\005 \001(\005\022\014\n\004text\030\006 \001" +
      "(\t\"R\n\tEventType\022\n\n\006INSERT\020\000\022\n\n\006DELETE\020\001\022" +
      "\010\n\004UNDO\020\002\022\010\n\004REDO\020\003\022\031\n\025CURSORLOCATIONCHA" +
      "NGED\020\004B\"\n\021edu.umich.penningB\rEventProtoc" +
      "ol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_penning_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_penning_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_penning_Event_descriptor,
              new java.lang.String[] { "UserID", "SessionID", "EventID", "Type", "CursorLocation", "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
